### ISSUE TITLE
Cosine similarity gives poor results

### ISSUE THREAD

**Issue by sanjita-suresh** [fursovia/geometric_embedding#1]
Thank you for the good work and sharing it.

I am working on semantically comparing 2 documents and I generated the sentence embeddings using GEM + Glove but when I use the cosine similarity to compare the embeddings its gives very poor similarity scores! I tried the steps in the readme , am I missing something?

**Comment by fursovia** [comment]
Hi @sanjita-suresh 

Could you please provide the code you used?

**Comment by sanjita-suresh** [comment]
```
embedding_matrix, vocab = get_embedding_matrix('../pretrained_embeddings/glove.6B.300d.txt')
embedder_ref = SentenceEmbedder(reference_en, embedding_matrix, vocab)
embedded_sentences_ref = embedder_ref.gem(window_size=3, sigma_power=1)
```
the embedded_sentences_ref is of shape (1000,300) and similar way the find the embeddings for other predicted 1000 sentences and the cosine similarity function is 

```
cosine_similarity(embedded_sentences_ref,embedded_sentences_pred)
```
the result of which is for example,
```
array([[ 0.54981997, -0.09919723, -0.07954745, ..., -0.06100615,
         0.01473607, -0.09207392],
       [-0.1350944 ,  0.56947164, -0.14292266, ..., -0.049508  ,
        -0.09836062, -0.12565233],
       [-0.04986341, -0.0395662 ,  0.61750237, ...,  0.07025331,
         0.00723754,  0.14313176],
```

**Comment by fursovia** [comment]
@sanjita-suresh make sure your sentences are lowercase. Also don't forget to delete extra symbols. Something like this should work:

```python
import re
reference_en = [re.sub(r"[^A-Za-z ]", "", sent).lower().strip() for sent in reference_en]
```

**Comment by sanjita-suresh** [comment]
@fursovia thank you for the suggestion but I am still getting almost the same cosine similarity(low and negatives) even after lower casing both reference and prediction sentences.

**Comment by fursovia** [comment]
@sanjita-suresh are you sure that `embedded_sentences_ref` and `embedded_sentences_pred` should have high similarity scores?

What kind of data was used to generate `embedded_sentences_ref` and `embedded_sentences_pred`? 

By the way, from your example of the matrix, I see that there are positive values on the diagonal.

**Comment by sanjita-suresh** [comment]
@fursovia the datasets are the machine translated english sentences and its reference . So yes they should have good scores.  
I also tried average word embeddings and it gave a pretty good score(~ 0.9) so was hoping to get better scores with GEM.

- reference sentences
```
'a man in an orange hat starring at something',
 'a boston terrier is running on lush green grass in front of a white fence',
 'a girl in karate uniform breaking a stick with a front kick',
 'people are fixing the roof of a house',
```
- predicted sentences
```
'a man in an orange hat presenting something',
 'a boston traveler runs across lush  green fence in front of a white fence',
 'a girl in a karate uniform is blocking a board with a kick',
 'people moving off the roof of a house',
```

**Comment by fursovia** [comment]
@sanjita-suresh I finally understand the problem.

Let's say we have true values (1s one the diagonal and -1s elsewhere). Cosine similarity is bounded between **-1** and **1**.

```python
true_values = np.diag(np.ones(similarities.shape[0])) * 2 - np.ones_like(similarities)

gem_similarities = cosine_similarity(gem_embeddings_ref, gem_embeddings_pred)
mean_similarities = cosine_similarity(mean_embeddings_ref, mean_embeddings_pred)
```

We should look not only on the diagonal, but on other values as well. Let's better check correlation between all similarities using Pearson correlation:

```python
true_values = true_values.flatten()
gem_similarities = gem_similarities.flatten()
mean_similarities = mean_similarities.flatten()

gem_corr = pearsonr(true_values, gem_similarities)[0]
mean_corr = pearsonr(true_values, mean_similarities)[0]
```

You will found out that `gem_corr > mean_corr` by a large constant, meaning that `GEM` provides better embeddings.

**Comment by sanjita-suresh** [comment]
@fursovia  Thank you for the explanation.

I also found the cosine similarity with the formula and it gives only the diagonal values.
```
similarity_gem =[]
for i in range(len(embedded_gem_ref)):
    similarity_gem.append(np.dot(embedded_gem_ref[i],embedded_gem_pred[i]) / (np.linalg.norm(embedded_gem_ref[i])*(np.linalg.norm(embedded_gem_pred[i]))))
```
the similarity scores with gem are 
```
[0.42640119529321224,
 0.5243667210857984,
 0.6201754128058088,
 0.5641207573761332,
```
and with mean are
```
[0.9517407833632348,
 0.9377522955381984,
 0.9538652824853595,
 0.9710610003736011,
```
I hope still the correlation to the true values is more with gem than with mean embeddings.

**Comment by fursovia** [comment]
@sanjita-suresh unfortunately, this setup of GEM embeddings give lower similarity scores between true pairs than mean embeddings. 

However, I don't understand why it is important for you. What is more important is that an algorithm should give not only high similarity scores between **true** pairs, but also give low similarity scores between **wrong** pairs. And this is not the case for mean embeddings.

What's your final task/problem?

**Comment by sanjita-suresh** [comment]
@fursovia  your explanation perfectly makes sense. 

My final task is to compare the correlation with the human annotation scores but I don't have the human  scores yet so wanted to make sure GEM scores are better correlated. 
Thank you.
